server:
    port: 8000
    servlet:
        context-path: /api
spring:
    datasource:
        url: jdbc:mysql://localhost:3307/films
        username: alan
        password: Anloba_And_Company_31
        initialization-mode: always
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
    flyway:
        url: ${spring.datasource.url}
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}
        baseline-on-migrate: true
        schemas: films
app:
    jwt:
        secret: ptitim
        durationMin: 60
